### ISSUE TITLE
Doesn't handle strings with spaces

### ISSUE THREAD

**Issue by AlgyTaylor** [anshulverma/cliqr#1]
Hi,

Your gem is awesome, but I have a bit of a problem. I want to create a command so that I can type something like:

    ruby logger write --source "Algy Taylor" --message "Here is my message"

But the CLIQR::Util.sanitize_args function strips out my lovely strings and so I get

    {
      source: "Algy",
      message: "Here"
    }

Is there a good reason for the args.split(' ') function? Isn't this already done by ARGV?  :)

**Comment by anshulverma** [comment]
Hi. Thanks for checking out `cliqr` and opening this issue.
You are correct, ARGV should take care of it already. I vaguely remember adding it for parsing shell mode commands. I will see if I can find some time later today to fix this one.

**Comment by AlgyTaylor** [comment]
Thanks, Anshul. cliqr's a really great idea, thanks for writing it!

**Comment by anshulverma** [comment]
Fixed in 11791f2b067963596da3fc197022132d86ed44ba

Please upgrade to version `2.1.1` (d2e4e223d36b85e0d31960fccb60f2e6cfec9d66) to get the fix.

Thanks.
